version: "3.8"

services: 
  app:
    build: .
    restart: always
    expose: 
      - '3000'
    ports: 
      - '3000:3000'
    volumes: 
      - '/app/node_modules'
      - '.:/app'
    environment: 
      - CHOKIDAR_USEPOLLING=true